const heroes = [
  {
    superhero: "Green Arrow",
    publisher: "DC Comics",
    alter_ego: "Oliver Queen",
    first_appearance: "More Fun Comics #73 (1941)",
    characters: "Black Canary, Speedy, Team Arrow",
    alt_img: "assets/heroes/dc-arrow.jpg",
  },
  {
    superhero: "Batman",
    publisher: "DC Comics",
    alter_ego: "Bruce Wayne",
    first_appearance: "Detective Comics #27 (1939)",
    characters: "Robin, Alfred Pennyworth, Commissioner Gordon",
    alt_img: "assets/heroes/dc-batman.jpg",
  },
  {
    superhero: "Black Canary",
    publisher: "DC Comics",
    alter_ego: "Dinah Lance",
    first_appearance: "Flash Comics #86 (1947)",
    characters: "Green Arrow, Birds of Prey",
    alt_img: "assets/heroes/dc-black.jpg",
  },
  {
    superhero: "Blue Beetle",
    publisher: "DC Comics",
    alter_ego: "Jaime Reyes",
    first_appearance: "Infinite Crisis #3 (2006)",
    characters: "Ted Kord, Booster Gold",
    alt_img: "assets/heroes/dc-blue.jpg",
  },
  {
    superhero: "The Flash",
    publisher: "DC Comics",
    alter_ego: "Barry Allen",
    first_appearance: "Showcase #4 (1956)",
    characters: "Kid Flash, Justice League",
    alt_img: "assets/heroes/dc-flash.jpg",
  },
  {
    superhero: "Green Lantern",
    publisher: "DC Comics",
    alter_ego: "Hal Jordan",
    first_appearance: "Showcase #22 (1959)",
    characters: "Justice League, Green Lantern Corps",
    alt_img: "assets/heroes/dc-green.jpg",
  },
  {
    superhero: "Martian Manhunter",
    publisher: "DC Comics",
    alter_ego: "J'onn J'onzz",
    first_appearance: "Detective Comics #225 (1955)",
    characters: "Justice League",
    alt_img: "assets/heroes/dc-martian.jpg",
  },
  {
    superhero: "Nightwing",
    publisher: "DC Comics",
    alter_ego: "Dick Grayson",
    first_appearance: "Detective Comics #38 (1940, as Robin)",
    characters: "Batman, Batgirl, Teen Titans",
    alt_img: "assets/heroes/dc-robin.jpg",
  },
  {
    superhero: "Superman",
    publisher: "DC Comics",
    alter_ego: "Clark Kent",
    first_appearance: "Action Comics #1 (1938)",
    characters: "Lois Lane, Jimmy Olsen, Justice League",
    alt_img: "assets/heroes/dc-superman.jpg",
  },
  {
    superhero: "Wonder Woman",
    publisher: "DC Comics",
    alter_ego: "Diana Prince",
    first_appearance: "All Star Comics #8 (1941)",
    characters: "Steve Trevor, Justice League",
    alt_img: "assets/heroes/dc-wonder.jpg",
  },
  {
    superhero: "Captain America",
    publisher: "Marvel Comics",
    alter_ego: "Steve Rogers",
    first_appearance: "Captain America Comics #1 (1941)",
    characters: "Bucky Barnes, Falcon, Avengers",
    alt_img: "assets/heroes/marvel-captain.jpg",
  },
  {
    superhero: "Cyclops",
    publisher: "Marvel Comics",
    alter_ego: "Scott Summers",
    first_appearance: "X-Men #1 (1963)",
    characters: "Jean Grey, X-Men",
    alt_img: "assets/heroes/marvel-cyclops.jpg",
  },
  {
    superhero: "Daredevil",
    publisher: "Marvel Comics",
    alter_ego: "Matt Murdock",
    first_appearance: "Daredevil #1 (1964)",
    characters: "Foggy Nelson, Elektra",
    alt_img: "assets/heroes/marvel-daredevil.jpg",
  },
  {
    superhero: "Hawkeye",
    publisher: "Marvel Comics",
    alter_ego: "Clint Barton",
    first_appearance: "Tales of Suspense #57 (1964)",
    characters: "Black Widow, Avengers",
    alt_img: "assets/heroes/marvel-hawkeye.jpg",
  },
  {
    superhero: "Hulk",
    publisher: "Marvel Comics",
    alter_ego: "Bruce Banner",
    first_appearance: "The Incredible Hulk #1 (1962)",
    characters: "Betty Ross, Avengers",
    alt_img: "assets/heroes/marvel-hulk.jpg",
  },
  {
    superhero: "Iron Man",
    publisher: "Marvel Comics",
    alter_ego: "Tony Stark",
    first_appearance: "Tales of Suspense #39 (1963)",
    characters: "Pepper Potts, War Machine, Avengers",
    alt_img: "assets/heroes/marvel-iron.jpg",
  },
  {
    superhero: "Silver Surfer",
    publisher: "Marvel Comics",
    alter_ego: "Norrin Radd",
    first_appearance: "Fantastic Four #48 (1966)",
    characters: "Galactus, Fantastic Four",
    alt_img: "assets/heroes/marvel-silver.jpg",
  },
  {
    superhero: "Spider-Man",
    publisher: "Marvel Comics",
    alter_ego: "Peter Parker",
    first_appearance: "Amazing Fantasy #15 (1962)",
    characters: "Mary Jane Watson, Aunt May",
    alt_img: "assets/heroes/marvel-spider.jpg",
  },
  {
    superhero: "Thor",
    publisher: "Marvel Comics",
    alter_ego: "Thor Odinson",
    first_appearance: "Journey into Mystery #83 (1962)",
    characters: "Odin, Loki, Avengers",
    alt_img: "assets/heroes/marvel-thor.jpg",
  },
  {
    superhero: "Wolverine",
    publisher: "Marvel Comics",
    alter_ego: "James Howlett",
    first_appearance: "The Incredible Hulk #180 (1974)",
    characters: "X-Men, Professor X",
    alt_img: "assets/heroes/marvel-wolverine.jpg",
  },
];

module.exports = heroes;
